/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cleano.ui;

import com.mycompany.cleano.i18n.LanguageManager;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author abdurraihan
 */
public class PengaturanPanel extends javax.swing.JPanel {

    /**
     * Creates new form PengaturanPanel
     */
    public PengaturanPanel() {
        initComponents();
        applyLanguage();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PengaturanPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtusernamelama = new javax.swing.JTextField();
        txtusernamebaru = new javax.swing.JTextField();
        txtpasswordbaru = new javax.swing.JTextField();
        txtpasswordlama = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbtemaapp = new javax.swing.JComboBox<>();
        cmbbahasa = new javax.swing.JComboBox<>();
        btnrestore = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnbackup = new javax.swing.JButton();

        PengaturanPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Pengaturan");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Pengaturan Akun");

        jLabel5.setText("Username lama");

        jLabel6.setText("Password Lama");

        jLabel7.setText("Password Baru");

        jLabel8.setText("Username baru");

        txtusernamelama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernamelamaActionPerformed(evt);
            }
        });

        txtusernamebaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernamebaruActionPerformed(evt);
            }
        });

        txtpasswordbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordbaruActionPerformed(evt);
            }
        });

        txtpasswordlama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordlamaActionPerformed(evt);
            }
        });

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnsimpan)
                .addGap(181, 181, 181))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(69, 69, 69)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtusernamebaru, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtpasswordlama, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtusernamelama, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtpasswordbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtusernamelama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpasswordlama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtusernamebaru, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtpasswordbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)))
                .addComponent(btnsimpan)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Pengaturan Aplikasi");

        jLabel10.setText("Tema Aplikasi");

        jLabel11.setText("Bahasa");

        cmbtemaapp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbtemaapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtemaappActionPerformed(evt);
            }
        });

        cmbbahasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbbahasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbahasaActionPerformed(evt);
            }
        });

        btnrestore.setText("Restore");
        btnrestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestoreActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnbackup.setText("Backup");
        btnbackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(63, 63, 63)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbtemaapp, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cmbbahasa, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnbackup)
                .addGap(28, 28, 28)
                .addComponent(btnrestore)
                .addGap(35, 35, 35)
                .addComponent(btnreset)
                .addGap(77, 77, 77))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(cmbtemaapp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(cmbbahasa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnrestore)
                    .addComponent(btnreset)
                    .addComponent(btnbackup))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout PengaturanPanelLayout = new javax.swing.GroupLayout(PengaturanPanel);
        PengaturanPanel.setLayout(PengaturanPanelLayout);
        PengaturanPanelLayout.setHorizontalGroup(
            PengaturanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PengaturanPanelLayout.setVerticalGroup(
            PengaturanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PengaturanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PengaturanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbtemaappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtemaappActionPerformed
        // TODO add your handling code here:
        String tema = cmbtemaapp.getSelectedItem().toString();
    if (tema.equals("Dark")) {
        UIManager.put("Panel.background", new Color(40, 40, 40));
        UIManager.put("Label.foreground", Color.WHITE);
    } else {
        UIManager.put("Panel.background", Color.WHITE);
        UIManager.put("Label.foreground", Color.BLACK);
    }
    SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_cmbtemaappActionPerformed

    private void cmbbahasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbahasaActionPerformed
        // TODO add your handling code here:
         Object selectedItem = cmbbahasa.getSelectedItem();
    if (selectedItem == null) return; // cegah NullPointerException

    String selected = selectedItem.toString();
    if (selected.equals("Indonesia")) {
        LanguageManager.setLocale(new java.util.Locale("id"));
    } else {
        LanguageManager.setLocale(new java.util.Locale("en"));
    }

    applyLanguage(); // terjemahkan ulang
    SwingUtilities.updateComponentTreeUI(SwingUtilities.getWindowAncestor(this)); // refresh UI
    }//GEN-LAST:event_cmbbahasaActionPerformed

    private void btnbackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackupActionPerformed
        // TODO add your handling code here:
        try {
        Runtime.getRuntime().exec("mongodump --db cleano --out backup/");
        JOptionPane.showMessageDialog(null, "Backup berhasil.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Backup gagal: " + e.getMessage());
    }
    }//GEN-LAST:event_btnbackupActionPerformed

    private void txtusernamelamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernamelamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernamelamaActionPerformed

    private void txtpasswordlamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordlamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordlamaActionPerformed

    private void txtusernamebaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernamebaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernamebaruActionPerformed

    private void txtpasswordbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordbaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordbaruActionPerformed

    private void btnrestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrestoreActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:                                       
    txtusernamelama.setText("");
    txtpasswordlama.setText("");
    txtusernamebaru.setText("");
    txtpasswordbaru.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
          String usernameLama = txtusernamelama.getText();
    String passwordLama = txtpasswordlama.getText();
    String usernameBaru = txtusernamebaru.getText();
    String passwordBaru = txtpasswordbaru.getText();

    // Validasi sederhana
    if (usernameLama.isEmpty() || passwordLama.isEmpty() || usernameBaru.isEmpty() || passwordBaru.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi.");
        return;
    }

    com.mycompany.cleano.service.UserDao dao = new com.mycompany.cleano.service.UserDao();
    boolean berhasil = dao.updateUsernamePassword(usernameLama, passwordLama, usernameBaru, passwordBaru);

    if (berhasil) {
        JOptionPane.showMessageDialog(this, "Berhasil memperbarui akun.");
    } else {
        JOptionPane.showMessageDialog(this, "Username atau password lama salah.");
    }
    }//GEN-LAST:event_btnsimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PengaturanPanel;
    private javax.swing.JButton btnbackup;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnrestore;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cmbbahasa;
    private javax.swing.JComboBox<String> cmbtemaapp;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtpasswordbaru;
    private javax.swing.JTextField txtpasswordlama;
    private javax.swing.JTextField txtusernamebaru;
    private javax.swing.JTextField txtusernamelama;
    // End of variables declaration//GEN-END:variables

   private void applyLanguage() {
    // hapus listener sementara
    java.awt.event.ActionListener[] listeners = cmbbahasa.getActionListeners();
    for (java.awt.event.ActionListener l : listeners) {
        cmbbahasa.removeActionListener(l);
    }

    jLabel3.setText(LanguageManager.get("pengaturan.title"));
    jLabel4.setText(LanguageManager.get("pengaturan.account.title"));
    jLabel5.setText(LanguageManager.get("pengaturan.account.username.old"));
    jLabel6.setText(LanguageManager.get("pengaturan.account.password.old"));
    jLabel7.setText(LanguageManager.get("pengaturan.account.password.new"));
    jLabel8.setText(LanguageManager.get("pengaturan.account.username.new"));
    btnsimpan.setText(LanguageManager.get("pengaturan.account.save"));

    jLabel9.setText(LanguageManager.get("pengaturan.app.title"));
    jLabel10.setText(LanguageManager.get("pengaturan.app.theme"));
    jLabel11.setText(LanguageManager.get("pengaturan.app.language"));

    btnbackup.setText(LanguageManager.get("pengaturan.app.backup"));
    btnrestore.setText(LanguageManager.get("pengaturan.app.restore"));
    btnreset.setText(LanguageManager.get("pengaturan.app.reset"));

    // isi ulang bahasa tanpa trigger action
    cmbbahasa.removeAllItems();
    cmbbahasa.addItem("Indonesia");
    cmbbahasa.addItem("English");

    // set default jika belum dipilih
    cmbbahasa.setSelectedItem(LanguageManager.getLocale().getLanguage().equals("id") ? "Indonesia" : "English");

    // pasang kembali listener
    for (java.awt.event.ActionListener l : listeners) {
        cmbbahasa.addActionListener(l);
    }
}


}
